### ISSUE TITLE
Feature Request: Hidden sub paths

### ISSUE THREAD

**Issue by sagikazarmark** [leighmcculloch/vangen#1]
Mostly in case pre-stable modules, subpackages are sometimes removed, but for earlier versions we still need the meta information.

The idea is to have a `hiddenSubs` section which could behave the same way, but the generated module index would not list them as sub paths.

**Comment by leighmcculloch** [comment]
@sagikazarmark thanks for opening this issue. It sounds like a good scenario to address.

In terms of how to support it we could make each element in the list of fields either a simple string subfolder name like we have now or an object/map of params for a subfolder that we can add a parameter `hidden: true` and in the future expand with other parameters. I think it could look something like this:

```json
{
  "domain": "4d63.com",
  "repositories": [
    {
      "prefix": "optional",
      "subs": [
        "template",
        { "name": "tmpl", "hidden": true }
      ],
      "url": "https://github.com/leighmcculloch/go-optional"
    }
  ]
}
```

**Comment by sagikazarmark** [comment]
@leighmcculloch I think that's a great idea.

**Comment by leighmcculloch** [comment]
@sagikazarmark Would you be up for taking a crack at a PR adding it?

**Comment by sagikazarmark** [comment]
Sure thing!
