### ISSUE TITLE
How to import github repo with custom branch?

### ISSUE THREAD

**Issue by yzs981130** [leighmcculloch/vangen#11]
When I try to import a github repo `REPO_NAME`(e.g. `leighmcculloch/vangen`) with a custom branch `BRANCH_NAME`, I encounter the following problem.

The json is like

```json
{
    "domain": "xxx",
    "index": true,
    "repositories": [
      {
        "prefix": "xxx",
        "type": "git",
        "url": "REPO_NAME",
        "source": {
          "home": "https://github.com/REPO_NAME",
          "dir": "https://github.com/REPO_NAME/tree/BRANCH_NAME{/dir}",
          "file": "https://github.com/REPO_NAME/blob/BRANCH_NAME{/dir}/{file}#L{line}"
        },
        "website": {
          "url": "https://github.com/REPO_NAME"
        }
      }
    ]
 }
```

However, it turns out that if the `r.URL` begins with `github.com`, all the fields of `r.SourceURLs` will be ignored and reset. The corresponding code is 
https://github.com/leighmcculloch/vangen/blob/c9cbaf870c7e025d28d5fa4cfed0f02ec98b73a0/generate_package.go#L55-L62

And if I remove the `url` in the json, the generated HTML seems not working, because of the missing 3rd field of `go-import` in the meta, like `<meta name="go-import" content="DOMAIN/PREFIX git ">`

I'm confused that is it a bug or an unsupported feature for github repos with custom branch or if I misunderstood the usage of `vangen`.  And if is a bug or feature, I can send a pr for that.

**Comment by leighmcculloch** [comment]
This looks like a bug. PRs welcome!
