### ISSUE TITLE
Submodules links are broken when no prefix is defined

### ISSUE THREAD

**Issue by julienrbrt** [leighmcculloch/vangen#16]
When no prefix is supplied, the links it generates for submodules are invalid:

- https://github.com/cosmos/vanity/blob/main/api/index.html#L53-L56
- https://github.com/leighmcculloch/vangen/blob/master/generate_package.go#L34

**Comment by leighmcculloch** [comment]
Thanks for reporting the bug. We should be producing the URL outside the template using the `url.JoinPath` method.

**Comment by leighmcculloch** [comment]
@julienrbrt I've opened a fix here: https://github.com/leighmcculloch/vangen/pull/18. Could you try it out and see if that addresses the issue completely?
