### ISSUE TITLE
README have broken link to binaries

### ISSUE THREAD

**Issue by ptxmac** [leighmcculloch/vangen#7]
`curl https://raw.githubusercontent.com/leighmcculloch/vangen/binaries/mac/amd64/vangen` gives a 404

same issue for the Linux binaries

**Comment by leighmcculloch** [comment]
Whoops. Thanks for highlighting this. The README needs updating for sure.

**Comment by leighmcculloch** [comment]
Fixed in 9739869228a41dd1adb75a689cd57625fe4b0435! Thanks for opening the issue.
