### ISSUE TITLE
Update godoc.org to pkg.go.dev in generated html

### ISSUE THREAD

**Issue by h7kanna** [leighmcculloch/vangen#9]
Hi @leighmcculloch,

This might be a breaking change ( in the generated HTML will have pkg.go.dev instead of godoc.org).

As godoc.org now redirects to pkg.go.dev. Should the generator reflect it?

This is not needed per se, as it redirects automatically.

**Comment by leighmcculloch** [comment]
I think this is a good idea 👏🏻.

**Comment by leighmcculloch** [comment]
Maybe we should make the base URL configurable, defaulting to `https://pkg.go.dev`.

**Comment by h7kanna** [comment]
Cool, I can make this change and raise a PR. I liked vangen, nice tool. Thanks,

**Comment by leighmcculloch** [comment]
PRs welcome!
